### PR TITLE
non-matching fields with BytesMarshallable: warn, test

### LINKED ISSUE #334: Unreadable messages when marshalling object or generic fields containing BytesMarshallable
The following test case: https://gist.github.com/alamar/4c78d0b9bd9a2d41402662fbd6dccffa

When we have an Object/<T> field in a class, and the value of that field is BytesMarshallable but not SelfDescribingMarshallable, the type information is lost which will lead to undefined behavior upon deserialization. At least a warning should be printed in such cases.

Discovered together with @glukos

### PR DESCRIPTION
**Pull request by alamar**
fixes #334

### CODE REVIEW

**Comment by alamar** [comment]
See also #340

**Comment by minborg** [comment]
Here is an example of a static initializer warner:

```
public final class SomeWarner {

    private SomeWarner() {
    }

    static {
        System.out.println("Warn...");
    }

    static void warnOnce() {
        // Warning done in static block
    }

    // Call using SomeWarner.warnOnce()
    
}

```

**Comment by minborg** [comment]
The proposed solution works but consider using a static class

**Review by minborg — APPROVED** [review]

**Comment by alamar** [comment]
@minborg 
Unfortunately, `Warner` approach will not work, since we wish to parameterize the message with the offending class name.

**Pull request merged**
