### PR TITLE
Optimise length check BinaryWire.text(CharSequence) #848

### LINKED ISSUE #848: BinaryWire.text(CharSequence) with long strings inefficiently calls findUtf8Length() twice
Owing to the check for the concise representation of strings less than 32 utf-8 chars, the length check is called once in text() and once from CommonMappedBytes.writeUtf8()

This becomes expensive for long strings

A simple optimisation is to rely on CharSequence.length() as a pre-check - if CharSequence.length > 0x20 then there is no need to call findUtf8Length() in the first case.

### PR DESCRIPTION
**Pull request by gregallen**
Fixes #848

### CODE REVIEW

**Comment by tgd** [comment]
@gregallen thanks very much for putting this together - its appreciated. Please can you review and sign and the contributor agreement - https://chronicle.software/contributor-agreement/

**Comment by JerryShea** [comment]
@gregallen just changing base as PRs need to go into develop branch

**Comment by gregallen** [comment]
CA done

**Comment by tgd** [comment]
Thank you Greg - I have merged this via a separate PR and sent a separate mail with a follow up. Thanks again.

**Pull request closed without merging**
